version: 2.1
steps:
  - run:
      name: Testing application
      command: make test
      shell: /bin/bash
      working_directory: ~/my-app
      no_output_timeout: 30m
      environment:
        FOO: bar

  - run: echo 127.0.0.1 devhost | sudo tee -a /etc/hosts

  - run: |
      exit 1

  - run:
      name: alerting
      command: echo "etape precedente en erreur , check yo build"
      when: on_fail