version: 2.1
commands: # a reusable command with parameters
   print_pipeline_id:
      parameters:
         to:
           default: "circle_workflow_id"
           type: string
      steps:
         - run: echo "Workflow ID <<parameters.to>>"
jobs:
   my-job:
      docker:
         - image: cimg/base:stable
      steps:
         - greeting:
            to: "$CIRCLE_WORKFLOW_ID"
workflows:
   my-workflow:
      jobs:
         - my-job        
         
