version: 2.1
commands:
  print_pipeline_id:
    description: "A very simple command for demonstration purposes"
    steps:
      - run: echo << $CIRCLE_WORKFLOW_ID >>
jobs:
  myjob:
    docker:
      - image: "cimg/base:stable"
    steps:
      - print_pipeline_id: # invoke command "sayhello"